### ISSUE TITLE
HOW TO FIX "fatal error: tins/tins.h: No such file or directory"?

### ISSUE THREAD

**Issue by luckypoem** [BLumia/udptun#1]
HI.
```
root@ar:~/udptun# make
g++ client.cpp -c -g -std=c++11 -I./3rdparty/libtins/include/ -L./3rdparty/libtins/lib -ltins
client.cpp:15:23: fatal error: tins/tins.h: No such file or directory
 #include <tins/tins.h>
                       ^
compilation terminated.
Makefile:14: recipe for target 'client.o' failed
make: *** [client.o] Error 1
root@ar:~/udptun#
```

**Comment by BLumia** [comment]
Hi,

Please take a look at this path of this repo: `udptun/3rdparty/libtins/`

As I mentioned [here](https://github.com/BLumia/udptun/tree/master/3rdparty/libtins), I am using a library called [libtins](https://libtins.github.io/) to construct the packet header, so you need to get that lib first.

Just follow the instruction in libtins' official website(you only need to build it by yourself via `cmake`), download that library, place it to `udptun/3rdparty/libtins/` and build it. Then you are fine to build the **udptun** program without problem.

Hope that helps 😄 
Gary.

**Comment by luckypoem** [comment]
hi,
i see.
```
cd ~
git clone https://github.com/mfontanini/libtins
cd libtins
mkdir build
cd build
cmake ..
make && make install & ldconfig

cd ~/udptun
make
```
这次make不再遇错：
```
root@ar:~/udptun# make
g++ client.cpp -c -g -std=c++11 -I./3rdparty/libtins/include/ -L./3rdparty/libtins/lib -ltins
g++ client.o -g -std=c++11 -I./3rdparty/libtins/include/ -L./3rdparty/libtins/lib -ltins -o client.elf 
g++ server.cpp -c -g -std=c++11 -I./3rdparty/libtins/include/ -L./3rdparty/libtins/lib -ltins
g++ server.o -g -std=c++11 -I./3rdparty/libtins/include/ -L./3rdparty/libtins/lib -ltins -o server.elf 
Done
root@ar:~/udptun#
```

**Comment by luckypoem** [comment]
但是在mac上，make遇到另一个错误：
yudeMacBook-Air:udptun-by-blumia brite$ make
g++ client.cpp -c -g -std=c++11 -I./3rdparty/libtins/include/ -L./3rdparty/libtins/lib -ltins
clang: warning: -ltins: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L./3rdparty/libtins/lib' [-Wunused-command-line-argument]
In file included from client.cpp:14:
./socketwrapper.h:12:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
         ^
1 error generated.
make: *** [client.o] Error 1
yudeMacBook-Air:udptun-by-blumia brite$

之前，我已经如下运行：
cd ~
git clone https://github.com/mfontanini/libtins
cd libtins
mkdir build
cd build
cmake ..
make && make install
ldconfig

在ldconfig这步遇错，提示：
”-bash: ldconfig: command not found“。那么mac上，相当于ldconfig的命令是什么？

**Comment by luckypoem** [comment]
看了此文http://zgserver.com/mac-os-xldconfig.html ，在~/libtins/build/里面运行了：
sudo update_dyld_shared_cache
未遇错。
但是返回~/udptun-by-blumia/里面，运行make还是遇到上面一样的错误。怎么解决？

**Comment by BLumia** [comment]
正如提示所说：
```
In file included from client.cpp:14:
./socketwrapper.h:12:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
^
1 error generated.
```
缺少 `linux/if.h` 头文件。而这是linux专有的东西，mac中你可能需要寻找对应的替代品。
由于我自己从来也没有使用过 Mac 设备，故我也没办法提供 Mac 系统上的相应支持了（实在抱歉，mac太贵了...），可能需要您自己做一些资料查阅。

顺便，GitHub 的 issue [支持 Markdown 语法](https://guides.github.com/features/mastering-markdown/)，在你贴代码块/一段命令的时候，你可以尝试使用`\`` 符号来围住你的代码段以避免转义和方便阅读。
