### ISSUE TITLE
请问，windows下像openvpn那样建立一个tun设备，接管网络流量，可以付费支持吗？

### ISSUE THREAD

**Issue by bestmarx** [BLumia/udptun#3]
如果您有相关经验，可以电报沟通？

**Comment by BLumia** [comment]
抱歉，我没有 Windows 下此类相关的开发经验 :(

**Comment by bestmarx** [comment]
非常荣幸收到您的回复。太遗憾了，如果您有相关经验的技术朋友，可以介绍给我们。我们就想调用openvpn
windows下建立tun设备的模块，接管windows的网络流量。再次感谢您的回复。

Gary Wang <notifications@github.com> 于2020年2月16日周日 下午5:28写道：
