### ISSUE TITLE
大佬我看了你的这篇博客，由于是萌新不确定我的思路对不对

### ISSUE THREAD

**Issue by Z-J-X** [BLumia/udptun#5]
看了您的博客后我的理解创建一个隧道是不是这样的
![image](https://user-images.githubusercontent.com/49222032/147457647-94313b1a-9df4-4102-a5bc-1641d4cd2225.png)

**Comment by BLumia** [comment]
发送的实际流程就只是：iptable 把要联网的程序的流量路由到 TUN 设备，我们的程序读取 TUN 设备的数据包并转发到我们的服务端程序，服务端再（sNAT 后）塞到 TUN 设备里发出去。

其实如果能把程序跑起来的话，里面是可以看到数据流向的日志输出的 :)

**Comment by Z-J-X** [comment]
好的，谢谢哈，我去试试
